# Это дополнительный файл в дополнение к базовому docker-compose.yml
# Добавляет веб-сервер (Caddy) и средство мониторинга логов (dozzle) контейнеров для дебага
# У основного сервиса (app) указываем image для загрузки готового образа шп ghcr.io


services:
  app:
    image: ${APP_IMAGE}
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://127.0.0.1:${PROMETHEUS_PORT}/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s

  caddy:
    image: caddy:2.10.0
    restart: unless-stopped
    environment:
      - CADDY_DOMAIN_NAME
      - CADDY_LETSENCRYPT_EMAIL
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-config:/config
      - caddy-data:/data
      - ~/frontend/dist:/var/www/frontend
    ports:
      - "80:80"
      - "443:443"

  dozzle:
    image: amir20/dozzle:latest
    expose:
      - 8080
    environment:
      - DOZZLE_BASE=/dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  caddy-config:
  caddy-data:
