global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "booking-bot"
    static_configs:
      - targets: [ "app:9090" ]
    metrics_path: "/metrics"

  # Опционально: мониторинг PostgreSQL
  - job_name: "postgres"
    static_configs:
      - targets: [ "postgres_exporter:9187" ] # Требуется postgres_exporter
    metrics_path: "/metrics"

  # Опционально: мониторинг Redis  
  - job_name: "redis"
    static_configs:
      - targets: [ "redis_exporter:9121" ] # Требуется redis_exporter
