// Code generated by MockGen. DO NOT EDIT.
// Source: resourse_page.go
//
// Generated by this command:
//
//	mockgen -source=resourse_page.go -destination=api/mocks/mock_resource_page_deps.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	dto "github.com/yandex-development-1-team/go/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockfileUploader is a mock of fileUploader interface.
type MockfileUploader struct {
	ctrl     *gomock.Controller
	recorder *MockfileUploaderMockRecorder
	isgomock struct{}
}

// MockfileUploaderMockRecorder is the mock recorder for MockfileUploader.
type MockfileUploaderMockRecorder struct {
	mock *MockfileUploader
}

// NewMockfileUploader creates a new mock instance.
func NewMockfileUploader(ctrl *gomock.Controller) *MockfileUploader {
	mock := &MockfileUploader{ctrl: ctrl}
	mock.recorder = &MockfileUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileUploader) EXPECT() *MockfileUploaderMockRecorder {
	return m.recorder
}

// ActivateByURL mocks base method.
func (m *MockfileUploader) ActivateByURL(ctx context.Context, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateByURL", ctx, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateByURL indicates an expected call of ActivateByURL.
func (mr *MockfileUploaderMockRecorder) ActivateByURL(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateByURL", reflect.TypeOf((*MockfileUploader)(nil).ActivateByURL), ctx, url)
}

// DeactivateByURL mocks base method.
func (m *MockfileUploader) DeactivateByURL(ctx context.Context, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateByURL", ctx, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateByURL indicates an expected call of DeactivateByURL.
func (mr *MockfileUploaderMockRecorder) DeactivateByURL(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateByURL", reflect.TypeOf((*MockfileUploader)(nil).DeactivateByURL), ctx, url)
}

// Upload mocks base method.
func (m *MockfileUploader) Upload(ctx context.Context, src io.Reader, name, contentType string, size int64) (*dto.FileUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, src, name, contentType, size)
	ret0, _ := ret[0].(*dto.FileUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockfileUploaderMockRecorder) Upload(ctx, src, name, contentType, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockfileUploader)(nil).Upload), ctx, src, name, contentType, size)
}
