// Code generated by MockGen. DO NOT EDIT.
// Source: api_box.go
//
// Generated by this command:
//
//	mockgen -source=api_box.go -destination=mocks/mock_boxlister.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	models "github.com/yandex-development-1-team/go/internal/models"
)

// MockBoxLister is a mock of BoxLister interface.
type MockBoxLister struct {
	ctrl     *gomock.Controller
	recorder *MockBoxListerMockRecorder
	isgomock struct{}
}

// MockBoxListerMockRecorder is the mock recorder for MockBoxLister.
type MockBoxListerMockRecorder struct {
	mock *MockBoxLister
}

// NewMockBoxLister creates a new mock instance.
func NewMockBoxLister(ctrl *gomock.Controller) *MockBoxLister {
	mock := &MockBoxLister{ctrl: ctrl}
	mock.recorder = &MockBoxListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoxLister) EXPECT() *MockBoxListerMockRecorder {
	return m.recorder
}

// DeleteServiceSlots mocks base method.
func (m *MockBoxLister) DeleteServiceSlots(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceSlots", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceSlots indicates an expected call of DeleteServiceSlots.
func (mr *MockBoxListerMockRecorder) DeleteServiceSlots(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceSlots", reflect.TypeOf((*MockBoxLister)(nil).DeleteServiceSlots), ctx, id)
}

// GetServiceByID mocks base method.
func (m *MockBoxLister) GetServiceByID(ctx context.Context, serviceID int64) (*models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceByID", ctx, serviceID)
	ret0, _ := ret[0].(*models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceByID indicates an expected call of GetServiceByID.
func (mr *MockBoxListerMockRecorder) GetServiceByID(ctx, serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceByID", reflect.TypeOf((*MockBoxLister)(nil).GetServiceByID), ctx, serviceID)
}

// GetServices mocks base method.
func (m *MockBoxLister) GetServices(ctx context.Context, telegramID int64) ([]models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServices", ctx, telegramID)
	ret0, _ := ret[0].([]models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServices indicates an expected call of GetServices.
func (mr *MockBoxListerMockRecorder) GetServices(ctx, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServices", reflect.TypeOf((*MockBoxLister)(nil).GetServices), ctx, telegramID)
}

// GetServicesByStatus mocks base method.
func (m *MockBoxLister) GetServicesByStatus(ctx context.Context, status *models.ServiceStatus) ([]models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServicesByStatus", ctx, status)
	ret0, _ := ret[0].([]models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServicesByStatus indicates an expected call of GetServicesByStatus.
func (mr *MockBoxListerMockRecorder) GetServicesByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServicesByStatus", reflect.TypeOf((*MockBoxLister)(nil).GetServicesByStatus), ctx, status)
}

// SoftDeleteService mocks base method.
func (m *MockBoxLister) SoftDeleteService(ctx context.Context, serviceID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteService", ctx, serviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteService indicates an expected call of SoftDeleteService.
func (mr *MockBoxListerMockRecorder) SoftDeleteService(ctx, serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteService", reflect.TypeOf((*MockBoxLister)(nil).SoftDeleteService), ctx, serviceID)
}

// UpdateService mocks base method.
func (m *MockBoxLister) UpdateService(ctx context.Context, id int64, service *models.BoxUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateService", ctx, id, service)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateService indicates an expected call of UpdateService.
func (mr *MockBoxListerMockRecorder) UpdateService(ctx, id, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateService", reflect.TypeOf((*MockBoxLister)(nil).UpdateService), ctx, id, service)
}

// UpdateServiceSlots mocks base method.
func (m *MockBoxLister) UpdateServiceSlots(ctx context.Context, id int64, slots *models.BoxNewSlots) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceSlots", ctx, id, slots)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServiceSlots indicates an expected call of UpdateServiceSlots.
func (mr *MockBoxListerMockRecorder) UpdateServiceSlots(ctx, id, slots any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceSlots", reflect.TypeOf((*MockBoxLister)(nil).UpdateServiceSlots), ctx, id, slots)
}

// UpdateServiceStatus mocks base method.
func (m *MockBoxLister) UpdateServiceStatus(ctx context.Context, serviceID int64, status models.ServiceStatus) (*models.BoxUpdateStatusResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceStatus", ctx, serviceID, status)
	ret0, _ := ret[0].(*models.BoxUpdateStatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServiceStatus indicates an expected call of UpdateServiceStatus.
func (mr *MockBoxListerMockRecorder) UpdateServiceStatus(ctx, serviceID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceStatus", reflect.TypeOf((*MockBoxLister)(nil).UpdateServiceStatus), ctx, serviceID, status)
}
