// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=../../repository/interfaces.go -destination=mocks/mock_box_solution_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	sqlx "github.com/jmoiron/sqlx"
	gomock "go.uber.org/mock/gomock"

	models "github.com/yandex-development-1-team/go/internal/models"
	repository "github.com/yandex-development-1-team/go/internal/repository"
)

// MockStaffRepository is a mock of StaffRepository interface.
type MockStaffRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStaffRepositoryMockRecorder
	isgomock struct{}
}

// MockStaffRepositoryMockRecorder is the mock recorder for MockStaffRepository.
type MockStaffRepositoryMockRecorder struct {
	mock *MockStaffRepository
}

// NewMockStaffRepository creates a new mock instance.
func NewMockStaffRepository(ctrl *gomock.Controller) *MockStaffRepository {
	mock := &MockStaffRepository{ctrl: ctrl}
	mock.recorder = &MockStaffRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaffRepository) EXPECT() *MockStaffRepositoryMockRecorder {
	return m.recorder
}

// CreateStaff mocks base method.
func (m *MockStaffRepository) CreateStaff(ctx context.Context, userReq *models.UserAPI, hashPassword string) (*models.UserAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStaff", ctx, userReq, hashPassword)
	ret0, _ := ret[0].(*models.UserAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStaff indicates an expected call of CreateStaff.
func (mr *MockStaffRepositoryMockRecorder) CreateStaff(ctx, userReq, hashPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStaff", reflect.TypeOf((*MockStaffRepository)(nil).CreateStaff), ctx, userReq, hashPassword)
}

// GetUserByEmail mocks base method.
func (m *MockStaffRepository) GetUserByEmail(ctx context.Context, email string) (*models.UserWithAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*models.UserWithAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStaffRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStaffRepository)(nil).GetUserByEmail), ctx, email)
}

// MockTelegramUserRepository is a mock of TelegramUserRepository interface.
type MockTelegramUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTelegramUserRepositoryMockRecorder
	isgomock struct{}
}

// MockTelegramUserRepositoryMockRecorder is the mock recorder for MockTelegramUserRepository.
type MockTelegramUserRepositoryMockRecorder struct {
	mock *MockTelegramUserRepository
}

// NewMockTelegramUserRepository creates a new mock instance.
func NewMockTelegramUserRepository(ctrl *gomock.Controller) *MockTelegramUserRepository {
	mock := &MockTelegramUserRepository{ctrl: ctrl}
	mock.recorder = &MockTelegramUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelegramUserRepository) EXPECT() *MockTelegramUserRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockTelegramUserRepository) CreateUser(ctx context.Context, telegramID int64, userName, firstName, lastName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, telegramID, userName, firstName, lastName)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockTelegramUserRepositoryMockRecorder) CreateUser(ctx, telegramID, userName, firstName, lastName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockTelegramUserRepository)(nil).CreateUser), ctx, telegramID, userName, firstName, lastName)
}

// GetUserByTelegramID mocks base method.
func (m *MockTelegramUserRepository) GetUserByTelegramID(ctx context.Context, telegramID int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByTelegramID", ctx, telegramID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByTelegramID indicates an expected call of GetUserByTelegramID.
func (mr *MockTelegramUserRepositoryMockRecorder) GetUserByTelegramID(ctx, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByTelegramID", reflect.TypeOf((*MockTelegramUserRepository)(nil).GetUserByTelegramID), ctx, telegramID)
}

// IsAdmin mocks base method.
func (m *MockTelegramUserRepository) IsAdmin(ctx context.Context, telegramID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAdmin", ctx, telegramID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAdmin indicates an expected call of IsAdmin.
func (mr *MockTelegramUserRepositoryMockRecorder) IsAdmin(ctx, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAdmin", reflect.TypeOf((*MockTelegramUserRepository)(nil).IsAdmin), ctx, telegramID)
}

// UpdateUserGrade mocks base method.
func (m *MockTelegramUserRepository) UpdateUserGrade(ctx context.Context, telegramID int64, grade int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserGrade", ctx, telegramID, grade)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserGrade indicates an expected call of UpdateUserGrade.
func (mr *MockTelegramUserRepositoryMockRecorder) UpdateUserGrade(ctx, telegramID, grade any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserGrade", reflect.TypeOf((*MockTelegramUserRepository)(nil).UpdateUserGrade), ctx, telegramID, grade)
}

// MockBookingRepository is a mock of BookingRepository interface.
type MockBookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryMockRecorder
	isgomock struct{}
}

// MockBookingRepositoryMockRecorder is the mock recorder for MockBookingRepository.
type MockBookingRepositoryMockRecorder struct {
	mock *MockBookingRepository
}

// NewMockBookingRepository creates a new mock instance.
func NewMockBookingRepository(ctrl *gomock.Controller) *MockBookingRepository {
	mock := &MockBookingRepository{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepository) EXPECT() *MockBookingRepositoryMockRecorder {
	return m.recorder
}

// CreateBooking mocks base method.
func (m *MockBookingRepository) CreateBooking(ctx context.Context, b *models.Booking) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", ctx, b)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockBookingRepositoryMockRecorder) CreateBooking(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockBookingRepository)(nil).CreateBooking), ctx, b)
}

// GetAvailableSlots mocks base method.
func (m *MockBookingRepository) GetAvailableSlots(ctx context.Context, serviceID int, date time.Time) ([]time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableSlots", ctx, serviceID, date)
	ret0, _ := ret[0].([]time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableSlots indicates an expected call of GetAvailableSlots.
func (mr *MockBookingRepositoryMockRecorder) GetAvailableSlots(ctx, serviceID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableSlots", reflect.TypeOf((*MockBookingRepository)(nil).GetAvailableSlots), ctx, serviceID, date)
}

// GetBookingsByUserID mocks base method.
func (m *MockBookingRepository) GetBookingsByUserID(ctx context.Context, userID int64) ([]models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingsByUserID indicates an expected call of GetBookingsByUserID.
func (mr *MockBookingRepositoryMockRecorder) GetBookingsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsByUserID", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingsByUserID), ctx, userID)
}

// UpdateBookingStatus mocks base method.
func (m *MockBookingRepository) UpdateBookingStatus(ctx context.Context, bookingID int64, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBookingStatus", ctx, bookingID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBookingStatus indicates an expected call of UpdateBookingStatus.
func (mr *MockBookingRepositoryMockRecorder) UpdateBookingStatus(ctx, bookingID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookingStatus", reflect.TypeOf((*MockBookingRepository)(nil).UpdateBookingStatus), ctx, bookingID, status)
}

// MockApplicationRepository is a mock of ApplicationRepository interface.
type MockApplicationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationRepositoryMockRecorder
	isgomock struct{}
}

// MockApplicationRepositoryMockRecorder is the mock recorder for MockApplicationRepository.
type MockApplicationRepositoryMockRecorder struct {
	mock *MockApplicationRepository
}

// NewMockApplicationRepository creates a new mock instance.
func NewMockApplicationRepository(ctrl *gomock.Controller) *MockApplicationRepository {
	mock := &MockApplicationRepository{ctrl: ctrl}
	mock.recorder = &MockApplicationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationRepository) EXPECT() *MockApplicationRepositoryMockRecorder {
	return m.recorder
}

// CreateApplication mocks base method.
func (m *MockApplicationRepository) CreateApplication(ctx context.Context, req *models.ApplicationCreateRequest) (*models.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApplication", ctx, req)
	ret0, _ := ret[0].(*models.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApplication indicates an expected call of CreateApplication.
func (mr *MockApplicationRepositoryMockRecorder) CreateApplication(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApplication", reflect.TypeOf((*MockApplicationRepository)(nil).CreateApplication), ctx, req)
}

// DeleteApplication mocks base method.
func (m *MockApplicationRepository) DeleteApplication(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApplication", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApplication indicates an expected call of DeleteApplication.
func (mr *MockApplicationRepositoryMockRecorder) DeleteApplication(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApplication", reflect.TypeOf((*MockApplicationRepository)(nil).DeleteApplication), ctx, id)
}

// GetApplicationByID mocks base method.
func (m *MockApplicationRepository) GetApplicationByID(ctx context.Context, id int64) (*models.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApplicationByID", ctx, id)
	ret0, _ := ret[0].(*models.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApplicationByID indicates an expected call of GetApplicationByID.
func (mr *MockApplicationRepositoryMockRecorder) GetApplicationByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApplicationByID", reflect.TypeOf((*MockApplicationRepository)(nil).GetApplicationByID), ctx, id)
}

// GetApplications mocks base method.
func (m *MockApplicationRepository) GetApplications(ctx context.Context, filter models.ApplicationFilter) ([]models.Application, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApplications", ctx, filter)
	ret0, _ := ret[0].([]models.Application)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetApplications indicates an expected call of GetApplications.
func (mr *MockApplicationRepositoryMockRecorder) GetApplications(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApplications", reflect.TypeOf((*MockApplicationRepository)(nil).GetApplications), ctx, filter)
}

// UpdateApplication mocks base method.
func (m *MockApplicationRepository) UpdateApplication(ctx context.Context, id int64, req *models.ApplicationUpdateRequest) (*models.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateApplication", ctx, id, req)
	ret0, _ := ret[0].(*models.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateApplication indicates an expected call of UpdateApplication.
func (mr *MockApplicationRepositoryMockRecorder) UpdateApplication(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateApplication", reflect.TypeOf((*MockApplicationRepository)(nil).UpdateApplication), ctx, id, req)
}

// MockBoxSolutionRepository is a mock of BoxSolutionRepository interface.
type MockBoxSolutionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBoxSolutionRepositoryMockRecorder
	isgomock struct{}
}

// MockBoxSolutionRepositoryMockRecorder is the mock recorder for MockBoxSolutionRepository.
type MockBoxSolutionRepositoryMockRecorder struct {
	mock *MockBoxSolutionRepository
}

// NewMockBoxSolutionRepository creates a new mock instance.
func NewMockBoxSolutionRepository(ctrl *gomock.Controller) *MockBoxSolutionRepository {
	mock := &MockBoxSolutionRepository{ctrl: ctrl}
	mock.recorder = &MockBoxSolutionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoxSolutionRepository) EXPECT() *MockBoxSolutionRepositoryMockRecorder {
	return m.recorder
}

// CheckSlotAvailability mocks base method.
func (m *MockBoxSolutionRepository) CheckSlotAvailability(ctx context.Context, serviceID int64, slot models.BoxAvailableSlot) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSlotAvailability", ctx, serviceID, slot)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckSlotAvailability indicates an expected call of CheckSlotAvailability.
func (mr *MockBoxSolutionRepositoryMockRecorder) CheckSlotAvailability(ctx, serviceID, slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSlotAvailability", reflect.TypeOf((*MockBoxSolutionRepository)(nil).CheckSlotAvailability), ctx, serviceID, slot)
}

// CreateBox mocks base method.
func (m *MockBoxSolutionRepository) CreateBox(ctx context.Context, box *models.BoxCreate) (*models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBox", ctx, box)
	ret0, _ := ret[0].(*models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBox indicates an expected call of CreateBox.
func (mr *MockBoxSolutionRepositoryMockRecorder) CreateBox(ctx, box any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBox", reflect.TypeOf((*MockBoxSolutionRepository)(nil).CreateBox), ctx, box)
}

// DeleteServiceSlots mocks base method.
func (m *MockBoxSolutionRepository) DeleteServiceSlots(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceSlots", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceSlots indicates an expected call of DeleteServiceSlots.
func (mr *MockBoxSolutionRepositoryMockRecorder) DeleteServiceSlots(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceSlots", reflect.TypeOf((*MockBoxSolutionRepository)(nil).DeleteServiceSlots), ctx, id)
}

// GetAvailableSlotsByServiceID mocks base method.
func (m *MockBoxSolutionRepository) GetAvailableSlotsByServiceID(ctx context.Context, serviceID int64) ([]models.BoxAvailableSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableSlotsByServiceID", ctx, serviceID)
	ret0, _ := ret[0].([]models.BoxAvailableSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableSlotsByServiceID indicates an expected call of GetAvailableSlotsByServiceID.
func (mr *MockBoxSolutionRepositoryMockRecorder) GetAvailableSlotsByServiceID(ctx, serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableSlotsByServiceID", reflect.TypeOf((*MockBoxSolutionRepository)(nil).GetAvailableSlotsByServiceID), ctx, serviceID)
}

// GetServiceByID mocks base method.
func (m *MockBoxSolutionRepository) GetServiceByID(ctx context.Context, serviceID int64) (*models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceByID", ctx, serviceID)
	ret0, _ := ret[0].(*models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceByID indicates an expected call of GetServiceByID.
func (mr *MockBoxSolutionRepositoryMockRecorder) GetServiceByID(ctx, serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceByID", reflect.TypeOf((*MockBoxSolutionRepository)(nil).GetServiceByID), ctx, serviceID)
}

// GetServices mocks base method.
func (m *MockBoxSolutionRepository) GetServices(ctx context.Context, telegramID int64) ([]models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServices", ctx, telegramID)
	ret0, _ := ret[0].([]models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServices indicates an expected call of GetServices.
func (mr *MockBoxSolutionRepositoryMockRecorder) GetServices(ctx, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServices", reflect.TypeOf((*MockBoxSolutionRepository)(nil).GetServices), ctx, telegramID)
}

// GetServicesByStatus mocks base method.
func (m *MockBoxSolutionRepository) GetServicesByStatus(ctx context.Context, status *models.ServiceStatus) ([]models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServicesByStatus", ctx, status)
	ret0, _ := ret[0].([]models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServicesByStatus indicates an expected call of GetServicesByStatus.
func (mr *MockBoxSolutionRepositoryMockRecorder) GetServicesByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServicesByStatus", reflect.TypeOf((*MockBoxSolutionRepository)(nil).GetServicesByStatus), ctx, status)
}

// List mocks base method.
func (m *MockBoxSolutionRepository) List(ctx context.Context, query models.BoxList) (*models.BoxListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, query)
	ret0, _ := ret[0].(*models.BoxListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBoxSolutionRepositoryMockRecorder) List(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBoxSolutionRepository)(nil).List), ctx, query)
}

// SoftDeleteService mocks base method.
func (m *MockBoxSolutionRepository) SoftDeleteService(ctx context.Context, serviceID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteService", ctx, serviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteService indicates an expected call of SoftDeleteService.
func (mr *MockBoxSolutionRepositoryMockRecorder) SoftDeleteService(ctx, serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteService", reflect.TypeOf((*MockBoxSolutionRepository)(nil).SoftDeleteService), ctx, serviceID)
}

// UpdateService mocks base method.
func (m *MockBoxSolutionRepository) UpdateService(ctx context.Context, id int64, service *models.BoxUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateService", ctx, id, service)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateService indicates an expected call of UpdateService.
func (mr *MockBoxSolutionRepositoryMockRecorder) UpdateService(ctx, id, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateService", reflect.TypeOf((*MockBoxSolutionRepository)(nil).UpdateService), ctx, id, service)
}

// UpdateServiceSlots mocks base method.
func (m *MockBoxSolutionRepository) UpdateServiceSlots(ctx context.Context, id int64, slots *models.BoxNewSlots) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceSlots", ctx, id, slots)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServiceSlots indicates an expected call of UpdateServiceSlots.
func (mr *MockBoxSolutionRepositoryMockRecorder) UpdateServiceSlots(ctx, id, slots any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceSlots", reflect.TypeOf((*MockBoxSolutionRepository)(nil).UpdateServiceSlots), ctx, id, slots)
}

// UpdateServiceStatus mocks base method.
func (m *MockBoxSolutionRepository) UpdateServiceStatus(ctx context.Context, serviceID int64, status models.ServiceStatus) (*models.BoxUpdateStatusResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceStatus", ctx, serviceID, status)
	ret0, _ := ret[0].(*models.BoxUpdateStatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServiceStatus indicates an expected call of UpdateServiceStatus.
func (mr *MockBoxSolutionRepositoryMockRecorder) UpdateServiceStatus(ctx, serviceID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceStatus", reflect.TypeOf((*MockBoxSolutionRepository)(nil).UpdateServiceStatus), ctx, serviceID, status)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// ClearSession mocks base method.
func (m *MockSessionRepository) ClearSession(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearSession", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearSession indicates an expected call of ClearSession.
func (mr *MockSessionRepositoryMockRecorder) ClearSession(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearSession", reflect.TypeOf((*MockSessionRepository)(nil).ClearSession), ctx, userID)
}

// GetSession mocks base method.
func (m *MockSessionRepository) GetSession(ctx context.Context, userID int64) (*models.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, userID)
	ret0, _ := ret[0].(*models.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockSessionRepositoryMockRecorder) GetSession(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockSessionRepository)(nil).GetSession), ctx, userID)
}

// SaveSession mocks base method.
func (m *MockSessionRepository) SaveSession(ctx context.Context, userID int64, state string, data map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSession", ctx, userID, state, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSession indicates an expected call of SaveSession.
func (mr *MockSessionRepositoryMockRecorder) SaveSession(ctx, userID, state, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSession", reflect.TypeOf((*MockSessionRepository)(nil).SaveSession), ctx, userID, state, data)
}

// UpdateSessionState mocks base method.
func (m *MockSessionRepository) UpdateSessionState(ctx context.Context, userID int64, newState string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionState", ctx, userID, newState)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionState indicates an expected call of UpdateSessionState.
func (mr *MockSessionRepositoryMockRecorder) UpdateSessionState(ctx, userID, newState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionState", reflect.TypeOf((*MockSessionRepository)(nil).UpdateSessionState), ctx, userID, newState)
}

// MockSettingsRepository is a mock of SettingsRepository interface.
type MockSettingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsRepositoryMockRecorder
	isgomock struct{}
}

// MockSettingsRepositoryMockRecorder is the mock recorder for MockSettingsRepository.
type MockSettingsRepositoryMockRecorder struct {
	mock *MockSettingsRepository
}

// NewMockSettingsRepository creates a new mock instance.
func NewMockSettingsRepository(ctrl *gomock.Controller) *MockSettingsRepository {
	mock := &MockSettingsRepository{ctrl: ctrl}
	mock.recorder = &MockSettingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsRepository) EXPECT() *MockSettingsRepositoryMockRecorder {
	return m.recorder
}

// GetSettings mocks base method.
func (m *MockSettingsRepository) GetSettings(ctx context.Context) ([]models.SettingRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettings", ctx)
	ret0, _ := ret[0].([]models.SettingRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettings indicates an expected call of GetSettings.
func (mr *MockSettingsRepositoryMockRecorder) GetSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettings", reflect.TypeOf((*MockSettingsRepository)(nil).GetSettings), ctx)
}

// PutSettings mocks base method.
func (m *MockSettingsRepository) PutSettings(ctx context.Context, newSettings []models.Setting) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutSettings", ctx, newSettings)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutSettings indicates an expected call of PutSettings.
func (mr *MockSettingsRepositoryMockRecorder) PutSettings(ctx, newSettings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutSettings", reflect.TypeOf((*MockSettingsRepository)(nil).PutSettings), ctx, newSettings)
}

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokenRepository) Create(ctx context.Context, rt *models.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenRepositoryMockRecorder) Create(ctx, rt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Create), ctx, rt)
}

// CreateRefreshToken mocks base method.
func (m *MockRefreshTokenRepository) CreateRefreshToken(ctx context.Context, userID int64, token string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, userID, token, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockRefreshTokenRepositoryMockRecorder) CreateRefreshToken(ctx, userID, token, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockRefreshTokenRepository)(nil).CreateRefreshToken), ctx, userID, token, expiresAt)
}

// GetForUpdate mocks base method.
func (m *MockRefreshTokenRepository) GetForUpdate(ctx context.Context, tx *sqlx.Tx, token string) (*models.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForUpdate", ctx, tx, token)
	ret0, _ := ret[0].(*models.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForUpdate indicates an expected call of GetForUpdate.
func (mr *MockRefreshTokenRepositoryMockRecorder) GetForUpdate(ctx, tx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForUpdate", reflect.TypeOf((*MockRefreshTokenRepository)(nil).GetForUpdate), ctx, tx, token)
}

// Revoke mocks base method.
func (m *MockRefreshTokenRepository) Revoke(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRefreshTokenRepositoryMockRecorder) Revoke(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Revoke), ctx, token)
}

// MockSpecialProjectRepository is a mock of SpecialProjectRepository interface.
type MockSpecialProjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialProjectRepositoryMockRecorder
	isgomock struct{}
}

// MockSpecialProjectRepositoryMockRecorder is the mock recorder for MockSpecialProjectRepository.
type MockSpecialProjectRepositoryMockRecorder struct {
	mock *MockSpecialProjectRepository
}

// NewMockSpecialProjectRepository creates a new mock instance.
func NewMockSpecialProjectRepository(ctrl *gomock.Controller) *MockSpecialProjectRepository {
	mock := &MockSpecialProjectRepository{ctrl: ctrl}
	mock.recorder = &MockSpecialProjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecialProjectRepository) EXPECT() *MockSpecialProjectRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSpecialProjectRepository) Create(ctx context.Context, proj *models.SpecialProjectDB) (*models.SpecialProjectDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, proj)
	ret0, _ := ret[0].(*models.SpecialProjectDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSpecialProjectRepositoryMockRecorder) Create(ctx, proj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSpecialProjectRepository)(nil).Create), ctx, proj)
}

// Delete mocks base method.
func (m *MockSpecialProjectRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSpecialProjectRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSpecialProjectRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockSpecialProjectRepository) GetByID(ctx context.Context, id int64) (*models.SpecialProjectDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.SpecialProjectDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSpecialProjectRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSpecialProjectRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockSpecialProjectRepository) List(ctx context.Context, statusFilter *bool, searchQuery string, limit, offset int) ([]*models.SpecialProjectDB, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, statusFilter, searchQuery, limit, offset)
	ret0, _ := ret[0].([]*models.SpecialProjectDB)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSpecialProjectRepositoryMockRecorder) List(ctx, statusFilter, searchQuery, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSpecialProjectRepository)(nil).List), ctx, statusFilter, searchQuery, limit, offset)
}

// Update mocks base method.
func (m *MockSpecialProjectRepository) Update(ctx context.Context, id int64, update *models.SpecialProjectUpdate) (*models.SpecialProjectDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, update)
	ret0, _ := ret[0].(*models.SpecialProjectDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSpecialProjectRepositoryMockRecorder) Update(ctx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSpecialProjectRepository)(nil).Update), ctx, id, update)
}

// MockTxRepository is a mock of TxRepository interface.
type MockTxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTxRepositoryMockRecorder
	isgomock struct{}
}

// MockTxRepositoryMockRecorder is the mock recorder for MockTxRepository.
type MockTxRepositoryMockRecorder struct {
	mock *MockTxRepository
}

// NewMockTxRepository creates a new mock instance.
func NewMockTxRepository(ctrl *gomock.Controller) *MockTxRepository {
	mock := &MockTxRepository{ctrl: ctrl}
	mock.recorder = &MockTxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxRepository) EXPECT() *MockTxRepositoryMockRecorder {
	return m.recorder
}

// RunToTx mocks base method.
func (m *MockTxRepository) RunToTx(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunToTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunToTx indicates an expected call of RunToTx.
func (mr *MockTxRepositoryMockRecorder) RunToTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunToTx", reflect.TypeOf((*MockTxRepository)(nil).RunToTx), ctx, fn)
}

// MockResourcePageRepository is a mock of ResourcePageRepository interface.
type MockResourcePageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockResourcePageRepositoryMockRecorder
	isgomock struct{}
}

// MockResourcePageRepositoryMockRecorder is the mock recorder for MockResourcePageRepository.
type MockResourcePageRepositoryMockRecorder struct {
	mock *MockResourcePageRepository
}

// NewMockResourcePageRepository creates a new mock instance.
func NewMockResourcePageRepository(ctrl *gomock.Controller) *MockResourcePageRepository {
	mock := &MockResourcePageRepository{ctrl: ctrl}
	mock.recorder = &MockResourcePageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourcePageRepository) EXPECT() *MockResourcePageRepositoryMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockResourcePageRepository) BeginTx(ctx context.Context) (*sqlx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(*sqlx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockResourcePageRepositoryMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockResourcePageRepository)(nil).BeginTx), ctx)
}

// GetAllSummaries mocks base method.
func (m *MockResourcePageRepository) GetAllSummaries(ctx context.Context) ([]*models.ResourcePage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSummaries", ctx)
	ret0, _ := ret[0].([]*models.ResourcePage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSummaries indicates an expected call of GetAllSummaries.
func (mr *MockResourcePageRepositoryMockRecorder) GetAllSummaries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSummaries", reflect.TypeOf((*MockResourcePageRepository)(nil).GetAllSummaries), ctx)
}

// GetBySlug mocks base method.
func (m *MockResourcePageRepository) GetBySlug(ctx context.Context, slug string) (*models.ResourcePage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(*models.ResourcePage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockResourcePageRepositoryMockRecorder) GetBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockResourcePageRepository)(nil).GetBySlug), ctx, slug)
}

// GetBySlugTx mocks base method.
func (m *MockResourcePageRepository) GetBySlugTx(ctx context.Context, queryable repository.Queryable, slug string, lockForUpdate bool) (*models.ResourcePage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlugTx", ctx, queryable, slug, lockForUpdate)
	ret0, _ := ret[0].(*models.ResourcePage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlugTx indicates an expected call of GetBySlugTx.
func (mr *MockResourcePageRepositoryMockRecorder) GetBySlugTx(ctx, queryable, slug, lockForUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlugTx", reflect.TypeOf((*MockResourcePageRepository)(nil).GetBySlugTx), ctx, queryable, slug, lockForUpdate)
}

// UpdatePageContentAndLinksTx mocks base method.
func (m *MockResourcePageRepository) UpdatePageContentAndLinksTx(ctx context.Context, tx *sqlx.Tx, slug, title, content string, links []models.ResourcePageLink) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePageContentAndLinksTx", ctx, tx, slug, title, content, links)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePageContentAndLinksTx indicates an expected call of UpdatePageContentAndLinksTx.
func (mr *MockResourcePageRepositoryMockRecorder) UpdatePageContentAndLinksTx(ctx, tx, slug, title, content, links any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePageContentAndLinksTx", reflect.TypeOf((*MockResourcePageRepository)(nil).UpdatePageContentAndLinksTx), ctx, tx, slug, title, content, links)
}

// MockQueryable is a mock of Queryable interface.
type MockQueryable struct {
	ctrl     *gomock.Controller
	recorder *MockQueryableMockRecorder
	isgomock struct{}
}

// MockQueryableMockRecorder is the mock recorder for MockQueryable.
type MockQueryableMockRecorder struct {
	mock *MockQueryable
}

// NewMockQueryable creates a new mock instance.
func NewMockQueryable(ctrl *gomock.Controller) *MockQueryable {
	mock := &MockQueryable{ctrl: ctrl}
	mock.recorder = &MockQueryableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryable) EXPECT() *MockQueryableMockRecorder {
	return m.recorder
}

// ExecContext mocks base method.
func (m *MockQueryable) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecContext", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecContext indicates an expected call of ExecContext.
func (mr *MockQueryableMockRecorder) ExecContext(ctx, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecContext", reflect.TypeOf((*MockQueryable)(nil).ExecContext), varargs...)
}

// GetContext mocks base method.
func (m *MockQueryable) GetContext(ctx context.Context, dest any, query string, args ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, dest, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetContext", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetContext indicates an expected call of GetContext.
func (mr *MockQueryableMockRecorder) GetContext(ctx, dest, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, dest, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContext", reflect.TypeOf((*MockQueryable)(nil).GetContext), varargs...)
}

// SelectContext mocks base method.
func (m *MockQueryable) SelectContext(ctx context.Context, dest any, query string, args ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, dest, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SelectContext", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SelectContext indicates an expected call of SelectContext.
func (mr *MockQueryableMockRecorder) SelectContext(ctx, dest, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, dest, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectContext", reflect.TypeOf((*MockQueryable)(nil).SelectContext), varargs...)
}
