-- +goose Up
-- +goose StatementBegin
INSERT INTO applications (status, manager_id, form_answer_id, customer_name, contact_info, description) VALUES
('pending',
    (SELECT id FROM staff WHERE role = 'manager_1' LIMIT 1),
    'form-001', 'Алексей Морозов', '@alex_morozov',
    'Хотим организовать корпоратив на 50 человек с квестом и банкетом'),
('confirmed',
    (SELECT id FROM staff WHERE role = 'manager_2' LIMIT 1),
    'form-002', 'Мария Петрова', '@maria_petrova',
    'Нужен тимбилдинг для команды разработчиков, около 20 человек'),
('pending',
    (SELECT id FROM staff WHERE role = 'manager_3' LIMIT 1),
    'form-003', 'Дмитрий Захаров', '@dmitry_z',
    'Детский день рождения на 15 детей, возраст 7-10 лет'),
('cancelled',
    (SELECT id FROM staff WHERE role = 'manager_1' LIMIT 1),
    'form-004', 'Екатерина Смирнова', '@kate_smirnova',
    'Свадебный банкет на 100 человек, нужно оформление зала'),
('pending',
    (SELECT id FROM staff WHERE role = 'manager_2' LIMIT 1),
    'form-005', 'Николай Фёдоров', '@nikolay_fed',
    'Конференция для партнёров, около 80 участников, нужна техническая поддержка'),
('confirmed',
    (SELECT id FROM staff WHERE role = 'admin' LIMIT 1),
    'form-006', 'Ольга Белова', '@olga_belova',
    'Юбилей компании на 200 человек, фуршет и живая музыка'),
('pending',
    (SELECT id FROM staff WHERE role = 'manager_1' LIMIT 1),
    'form-007', 'Игорь Волков', '@igor_volkov',
    'Новогодний корпоратив на 70 человек, нужны аниматоры и DJ'),
('pending',
    (SELECT id FROM staff WHERE role = 'manager_3' LIMIT 1),
    'form-008', 'Светлана Козлова', '@svetlana_k',
    'Презентация нового продукта для клиентов, около 40 человек'),
('cancelled',
    (SELECT id FROM staff WHERE role = 'manager_2' LIMIT 1),
    'form-009', 'Андрей Новиков', '@andrey_nov',
    'Тренинг по продажам для сотрудников, 25 человек'),
('confirmed',
    (SELECT id FROM staff WHERE role = 'admin' LIMIT 1),
    'form-010', 'Татьяна Соколова', '@tatyana_sok',
    'Выпускной вечер для школы, 120 человек, нужен банкет и фотограф'),
('pending',
    (SELECT id FROM staff WHERE role = 'manager_1' LIMIT 1),
    'form-011', 'Виктор Попов', '@viktor_popov',
    'Деловой завтрак с партнёрами, 15 человек'),
('pending',
    (SELECT id FROM staff WHERE role = 'manager_2' LIMIT 1),
    'form-012', 'Анна Лебедева', '@anna_leb',
    'Детский праздник на 25 детей, аниматоры и торт'),
('confirmed',
    (SELECT id FROM staff WHERE role = 'manager_3' LIMIT 1),
    'form-013', 'Роман Семёнов', '@roman_sem',
    'Корпоративный пикник на природе, 60 человек'),
('pending',
    (SELECT id FROM staff WHERE role = 'admin' LIMIT 1),
    'form-014', 'Юлия Михайлова', '@julia_m',
    'Фотосессия с командой и небольшой фуршет, 30 человек'),
('cancelled',
    (SELECT id FROM staff WHERE role = 'manager_1' LIMIT 1),
    'form-015', 'Павел Орлов', '@pavel_orl',
    'Мастер-класс по кулинарии для сотрудников, 18 человек'),
('confirmed',
    (SELECT id FROM staff WHERE role = 'manager_2' LIMIT 1),
    'form-016', 'Валентина Крылова', '@val_krylova',
    'Свадьба на 80 человек, выездная регистрация и банкет'),
('pending',
    (SELECT id FROM staff WHERE role = 'manager_3' LIMIT 1),
    'form-017', 'Денис Зайцев', '@denis_z',
    'Квиз для команды, около 50 участников'),
('pending',
    (SELECT id FROM staff WHERE role = 'admin' LIMIT 1),
    'form-018', 'Наталья Соловьёва', '@natasha_sol',
    'Открытие нового офиса, 90 гостей, фуршет и экскурсия'),
('pending',
    (SELECT id FROM staff WHERE role = 'manager_1' LIMIT 1),
    'form-019', 'Артём Борисов', '@artem_bor',
    'День рождения ребёнка, 10 детей, квест и аниматор'),
('confirmed',
    (SELECT id FROM staff WHERE role = 'manager_2' LIMIT 1),
    'form-020', 'Ксения Фролова', '@kseniya_f',
    'Корпоратив на Новый год, 45 человек, ресторан'),
('pending',
    (SELECT id FROM staff WHERE role = 'manager_3' LIMIT 1),
    'form-021', 'Максим Комаров', '@max_komarov',
    'Тимбилдинг на природе, 35 человек, верёвочный курс'),
('cancelled',
    (SELECT id FROM staff WHERE role = 'admin' LIMIT 1),
    'form-022', 'Алина Васильева', '@alina_vas',
    'Фуршет после конференции, 60 человек'),
('pending',
    (SELECT id FROM staff WHERE role = 'manager_1' LIMIT 1),
    'form-023', 'Сергей Жуков', '@sergey_zhuk',
    'Юбилей 50 лет, семейный праздник на 40 человек'),
('confirmed',
    (SELECT id FROM staff WHERE role = 'manager_2' LIMIT 1),
    'form-024', 'Марина Степанова', '@marina_step',
    'Корпоративный выезд на 2 дня, 55 человек'),
('pending',
    (SELECT id FROM staff WHERE role = 'manager_3' LIMIT 1),
    'form-025', 'Кирилл Макаров', '@kirill_mak',
    'Презентация для инвесторов, 20 человек, переговорная'),
('confirmed',
    (SELECT id FROM staff WHERE role = 'admin' LIMIT 1),
    'form-026', 'Елена Никитина', '@elena_nik',
    'Выставка продукции компании, 150 посетителей'),
('pending',
    (SELECT id FROM staff WHERE role = 'manager_1' LIMIT 1),
    'form-027', 'Олег Титов', '@oleg_titov',
    'Мастер-класс по живописи, 12 человек'),
('pending',
    (SELECT id FROM staff WHERE role = 'manager_2' LIMIT 1),
    'form-028', 'Дарья Кузнецова', '@dasha_kuz',
    'Детский лагерь однодневный, 30 детей, квесты и спорт'),
('cancelled',
    (SELECT id FROM staff WHERE role = 'manager_3' LIMIT 1),
    'form-029', 'Евгений Громов', '@evg_gromov',
    'Банкет на юбилей организации, 110 человек'),
('confirmed',
    (SELECT id FROM staff WHERE role = 'admin' LIMIT 1),
    'form-030', 'Полина Ершова', '@polina_er',
    'Новогодний праздник для детей сотрудников, 40 детей'),
('pending',
    (SELECT id FROM staff WHERE role = 'manager_1' LIMIT 1),
    'form-031', 'Тимур Исаев', '@timur_is',
    'Спортивный день компании, 80 человек, эстафеты'),
('pending',
    (SELECT id FROM staff WHERE role = 'manager_2' LIMIT 1),
    'form-032', 'Вероника Панова', '@veronika_p',
    'Свадебный фуршет, 55 человек, выездное обслуживание'),
('confirmed',
    (SELECT id FROM staff WHERE role = 'manager_3' LIMIT 1),
    'form-033', 'Богдан Рыбаков', '@bogdan_ryb',
    'Корпоратив с квестом, 38 человек'),
('pending',
    (SELECT id FROM staff WHERE role = 'admin' LIMIT 1),
    'form-034', 'Людмила Громова', '@lyudmila_gr',
    'Праздник для пенсионеров компании, 25 человек, тихий банкет'),
('cancelled',
    (SELECT id FROM staff WHERE role = 'manager_1' LIMIT 1),
    'form-035', 'Фёдор Зимин', '@fedor_zim',
    'Хэллоуин-вечеринка, 65 человек, костюмы и декор');
-- +goose StatementEnd
 
-- +goose Down
-- +goose StatementBegin
DELETE FROM applications WHERE form_answer_id IN (
    'form-001','form-002','form-003','form-004','form-005',
    'form-006','form-007','form-008','form-009','form-010',
    'form-011','form-012','form-013','form-014','form-015',
    'form-016','form-017','form-018','form-019','form-020',
    'form-021','form-022','form-023','form-024','form-025',
    'form-026','form-027','form-028','form-029','form-030',
    'form-031','form-032','form-033','form-034','form-035'
);
-- +goose StatementEnd